services:
  - type: web
    name: althara-news-service
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
